#! /bin/bash
set -e

PROJECT_ROOT=$(pwd)
BUILD_DIR="open62541_build"

cmake -B $BUILD_DIR $PROJECT_ROOT/open62541/ -DBUILD_SHARED_LIBS=ON -DUA_ENABLE_INLINABLE_EXPORT=ON -DUA_ENABLE_ENCRYPTION=MBEDTLS -DCMAKE_INSTALL_PREFIX=install -DUA_BUILD_EXAMPLES=OFF -DUA_BUILD_UNIT_TESTS=OFF -DUA_ENABLE_AMALGAMATION=ON -DUA_MULTITHREADING=0 -DUA_LOGLEVEL=100 -DUA_ENABLE_AMALGAMATION=ON
cmake --build $BUILD_DIR -j 12

cp $PROJECT_ROOT/$BUILD_DIR/bin/libopen62541.* $PROJECT_ROOT/lib/ # library files
