#! /bin/bash
set -e

PROJECT_ROOT=$(pwd)
BUILD_DIR="open62541_build"
rm -rf $BUILD_DIR
mkdir $BUILD_DIR
cd $BUILD_DIR
cmake $PROJECT_ROOT/open62541/ -DBUILD_SHARED_LIBS=ON -DUA_ENABLE_INLINABLE_EXPORT=ON -DCMAKE_INSTALL_PREFIX=install -DUA_BUILD_EXAMPLES=OFF -DUA_BUILD_UNIT_TESTS=OFF -DUA_ENABLE_AMALGAMATION=ON -DUA_MULTITHREADING=0 -DUA_LOGLEVEL=100 -DUA_ENABLE_ENCRYPTION=MBEDTLS
cmake --build $PROJECT_ROOT/$BUILD_DIR -j 12
patch open62541.h -i $PROJECT_ROOT/remove_bitfields.patch
cd $PROJECT_ROOT

# Update the flutter project
dart run ffigen # Bindings
cp $PROJECT_ROOT/$BUILD_DIR/bin/libopen62541.* $PROJECT_ROOT/lib/ # library files
