name: open62541
description: OPC UA stack, bindings to the open62541 library.
version: 0.0.0-dev.1
repository: https://github.com/centroid-is/open62541_dart

environment:
  sdk: ^3.6.0
dependencies:
  binarize: ^2.0.0
  collection: ^1.19.0
  ffi: ^2.1.2
  tuple: ^2.0.2
platforms:
  linux:
topics:
  - network
  - industrial
  - opcua
  - open62541
  - hmi
dev_dependencies:
  ffigen: ^18.1.0
  lints: ^5.1.1
  test: ^1.24.0
  import_sorter: ^4.6.0
import_sorter:
  emojis: false
  comments: false
  ignored_files: 
    - open62541_bindings.dart
ffigen:
  output: lib/src/generated/open62541_bindings.dart
  name: open62541
  description: Low level bindings to open62541
  headers:
    entry-points:
      - 'open62541_build/open62541.h'
  functions:
    symbol-address:
      include:
        - 'UA_*' # Do this to expose all function pointers.
        - '__UA_Client_AsyncService'
    rename:
      '__UA_Client_AsyncService': 'UA_Client_AsyncService'
  # UA_TYPES is a list inside the library and we need raw access
  # To the top level pointer to increment the list.
  globals:
    symbol-address:
      include:
        - 'UA_TYPES'
  compiler-opts:
    - '-Iopen62541_build/install/include/'
    - '-I/lib/clang/19/include/'
    - '-Wno-nullability-completeness'
    - '-Wno-expansion-to-defined'
    - '-DUA_ENABLE_ENCRYPTION' 
